"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['VisoarAgExplorer.py']
APP_NAME = "ViSOAR Ag Explorer"
DATA_FILES = ['userFileHistory.xml']
OPTIONS = {
	'packages': ['numpy', 'OpenVisus' ]
	'plist': {
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleGetInfoString': "Stitching and Visualizing Aerial Photos",
        'CFBundleIdentifier': "com.visus.osx.visoar",
        'CFBundleVersion': "0.1.0",
        'CFBundleShortVersionString': "0.1.0",
        'NSHumanReadableCopyright': u"Copyright © 2020, ViSUS LLC, All Rights Reserved"
    	}
	}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
